extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_f3d_material_layer1_area1_lights;
extern u8 castle_grounds_dl_RMGP01_9b1a69aa_14_mip2_ci8[];
extern u8 castle_grounds_dl_RMGP01_9b1a69aa_14_mip2_ci8_pal_rgba16[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_f3d_material_layer1_area1[];
extern Gfx mat_revert_castle_grounds_dl_f3d_material_layer1_area1[];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
