extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_coffin_side_001_lights;
extern Lights1 castle_grounds_dl_sticky_face_002_layer1_lights;
extern Lights1 castle_grounds_dl_f3d_material_layer1_area1_lights;
extern u8 castle_grounds_dl_model266_ci4[];
extern u8 castle_grounds_dl_model266_ci4_pal_rgba16[];
extern u8 castle_grounds_dl_n64lc_tunnel_rgba16[];
extern u8 castle_grounds_dl_web_i4[];
extern u8 castle_grounds_dl_RMGP01_9b1a69aa_14_mip2_ci8[];
extern u8 castle_grounds_dl_RMGP01_9b1a69aa_14_mip2_ci8_pal_rgba16[];
extern Vtx castle_grounds_dl_main_004_mesh_layer_1_vtx_0[44];
extern Gfx castle_grounds_dl_main_004_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_main_004_mesh_layer_1_vtx_1[61];
extern Gfx castle_grounds_dl_main_004_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_coffin_side_001[];
extern Gfx mat_revert_castle_grounds_dl_coffin_side_001[];
extern Gfx mat_castle_grounds_dl_sticky_face_002_layer1[];
extern Gfx mat_revert_castle_grounds_dl_sticky_face_002_layer1[];
extern Gfx mat_castle_grounds_dl_f3d_material_layer1_area1[];
extern Gfx mat_revert_castle_grounds_dl_f3d_material_layer1_area1[];
extern Gfx castle_grounds_dl_main_004_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
